### ISSUE TITLE
Improved geo assignment

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/watchman#117]
We need to clean up the geo assignment for our tweets:

- [ ] Create priority list of extracted locations
- [ ] If tweet has geo, look for anchors
- [ ] Prefer early locations inside events
- [ ] Limit locations which are visualized

**Comment by lukewendling** [comment]
this might be a good candidate for a github Project. i created a sample project as example. basically u add multiple issues under a larger project. allows for faster PRs and quicker releases of working code. @justinlueders

**Comment by justinlueders** [comment]
so like an epic
