### ISSUE TITLE
Remove Word cloud

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/watchman#119]
Have the event visualization reflect what we are storing in mongo/sending to uncharted more accurately by using the keywords supplied in Dr. M.

**Comment by lukewendling** [comment]
Looks like dr-manhattan already creates a dict of keyword -> count. i'm updating the codes to post that data structure to the api. then add qcr-specific formatting further downstream.

**Comment by lukewendling** [comment]
i'll replace the wordcloud with simple tabular data.
