### ISSUE TITLE
Move Dr-Manhattan run to a Job Monitor so errors bubble up

### ISSUE THREAD

**Issue by justinlueders** [Sotera/watchman#120]

**Comment by justinlueders** [comment]
Do we really want to do this?  This would cause Dr Man to take up a slot in the kue when it's not really required.  Event finding is basically a stand alone process that can run at any time.

**Comment by justinlueders** [comment]
I don't think we should do this any more.  If we move Dr Manhattan to a job it will keep the jobset from finishing.  I think we should keep the flow the way it is and maybe revisit the code to make it cleaner.  Thoughts?

**Comment by lukewendling** [comment]
@justinlueders yeah def agree. with spark now an alternative to Loopy-heavy code like dr-man, we can make that svc fast enough to be in a monitor. but prob not until then. for now, better to have it be unmanned, to prevent backlog.
