### ISSUE TITLE
Hashtag Bayesian likelihood filter

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/watchman#54]
Presently, our signal is drowned out by the persistent noise of twitter.  To ensure that we emphasise events, we will use a Bayesian likelihood filter on hashtag terms.  This should have two effects:

1.) Normalize the importance hashtags:  We will model the number of hashtag terms with a poisson distribution, and use a cumulative probability to characterize the importance of this number of terms.  This puts all hashtag cluster weights on a 0 - 1 scale.

2.) Terminate events: Events are merged across time windows.  Since hashtags persists across most time windows, events rarely terminate, and we create one large highly connected graph.  Killing large, persistent nodes will make events more localized in time.

**Comment by lukewendling** [comment]
also (or maybe said another way) this should (right?) reduce num of aggregate clusters and/or the num of both similar_post_ids + post_clusters_ids in each agg cluster -> huge storage savings in mongo.

**Comment by drJAGartner** [comment]
Yes, it should reduce the number of post cluster ids and similar post ids, since many post clusters will no longer be included.
