### ISSUE TITLE
Item in list query

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/watchman#55]
Currently, there is no ability to perform a 'where' query in which one tries to find an item in a list.  This specifically comes into place when attempting to find socialMediaPosts that have a specific hashtag term.  I'm not sure how painful this would be to implement, but it would be a nice feature to have.

**Comment by lukewendling** [comment]
@drJAGartner i think ur trying to find a specific tag in the .hashtags array field in smposts yeah? if so, I thought u could with something like http://stackoverflow.com/questions/18148166/find-document-with-array-that-contains-a-specific-value

basically the same syntax as a regular scalar value

**Comment by drJAGartner** [comment]
@lukewendling I'll check this out.

**Comment by lukewendling** [comment]
nudge @drJAGartner
