### ISSUE TITLE
Job Monitor delayed start

### ISSUE THREAD

**Issue by justinlueders** [Sotera/watchman#56]
We need a system that will poll the job monitor collection watching for jobs that have sufficient data to be processed.
steps would be on a timer:

* Is a job monitor running?
  * Yes: return
  * No: Get the earliest, non complete, non timed out job in the collection
    * do we have enough SMP to process this job?
      * Yes: Have we gotten a SMP in the last n minutes?
        * Yes: return
        * No: Run the job!
      * No: Have we passed our timeout for this window?
        * Yes: time the job out and ignore it.
        * No: return

**Comment by lukewendling** [comment]
JobSet is going to be rad! @justinlueders

**Comment by lukewendling** [comment]
related to #57

**Comment by lukewendling** [comment]
closed by #57
