### ISSUE TITLE
Link watchmen events to news events (as provided by QCR)

### ISSUE THREAD

**Issue by drJAGartner** [Sotera/watchman#71]
One of our collaborators has an array of scrapers creating geo events based on stories by major new outlets.  This information is available in a mongo db on the QCR system, and as such, we would like to see if we are able to link these stories to our events by either linking headline keywords to event keywords, or by direct comparison of URLs.

We can discuss this more on Monday.

**Comment by lukewendling** [comment]
assume u mean 'news' here @drJAGartner

**Comment by drJAGartner** [comment]
Yes, they have scrapers for places like the Guardian, BBC, etc.

**Comment by justinlueders** [comment]
this basically went unused...closing...
we can re-open if anyone cares
