### ISSUE TITLE
Feature sim clustering: Unused data_type job param in Loopy query?

### ISSUE THREAD

**Issue by lukewendling** [Sotera/watchman#75]
See https://github.com/Sotera/watchman/blob/master/services/feature-similarity-clustering/main.py#L38

Sanity check: should we be using job['data_type'] in the Loopy query params? 

I noticed during a system run that the clustering step was taking a really long time. It is scrolling thru more records that I'd expect (more than the featurizer step) b/c it doesn't filter by data_type.

What am i missing? @drJAGartner @justinlueders

**Comment by drJAGartner** [comment]
It certainly should be only getting smp of a single type

**Comment by lukewendling** [comment]
Fixed by f8dcc7f
