### ISSUE TITLE
Bug: Runtime error in caffe featurizer with non-gpu dockerfile

### ISSUE THREAD

**Issue by lukewendling** [Sotera/watchman#80]
build error says can't build in gpu mode, which i guess is determined by linux (ubuntu) host?

**Comment by justinlueders** [comment]
Evidently they are having issues with certificates...this line solved the issue

RUN CONDA_SSL_VERIFY=false conda update pyopenssl

**Comment by lukewendling** [comment]
Just realized this wasn't a build problem but a runtime bug with error: 

```
F0103 17:33:12.748132     1 conv_layer.cpp:76] Cannot use GPU in CPU-only Caffe: check mode.
```

To re-create: run image featurizing on non-gpu ubuntu.

**Comment by lukewendling** [comment]
fixed in branch 65 using env var for gpu enabling vs. a hard-coded proc file
